# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1248, 595)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 101, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 101, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        MainWindow.setPalette(palette)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logoMI.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 101, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(76, 101, 150))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 66, 66))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(52, 52, 52))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.SearchBar = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.SearchBar.setStyleSheet("color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 6px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"margin-bottom: 0px;")
        self.SearchBar.setFrame(True)
        self.SearchBar.setObjectName("SearchBar")
        self.verticalLayout.addWidget(self.SearchBar)
        self.searchButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.searchButton.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.searchButton.setFont(font)
        self.searchButton.setStyleSheet("QPushButton{\n"
"\n"
"color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 7px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"    margin-top: 0px;\n"
"}\n"
"\n"
":hover{\n"
"background-color:black;\n"
"}")
        self.searchButton.setAutoDefault(False)
        self.searchButton.setDefault(False)
        self.searchButton.setFlat(False)
        self.searchButton.setObjectName("searchButton")
        self.verticalLayout.addWidget(self.searchButton)
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Cantarell Light")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.tagBox = QtWidgets.QComboBox(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.tagBox.setFont(font)
        self.tagBox.setStyleSheet("QComboBox{\n"
"color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 6px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"   border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"}")
        self.tagBox.setObjectName("tagBox")
        self.verticalLayout.addWidget(self.tagBox)
        self.ManageTagsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.ManageTagsButton.setFont(font)
        self.ManageTagsButton.setStyleSheet("QPushButton{\n"
"\n"
"color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 7px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"    margin-top: 0px;\n"
"}\n"
"\n"
":hover{\n"
"background-color:black;\n"
"}")
        self.ManageTagsButton.setObjectName("ManageTagsButton")
        self.verticalLayout.addWidget(self.ManageTagsButton)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(200, 65))
        self.label.setStyleSheet("\n"
"    margin: 10px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("logoMI-Text.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.notifFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.notifFrame.setStyleSheet("QFrame{\n"
"    background-color: #246EDB;\n"
"    padding: 2px 6px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 0px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"}")
        self.notifFrame.setObjectName("notifFrame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.notifFrame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.notifIcon = QtWidgets.QLabel(parent=self.notifFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notifIcon.sizePolicy().hasHeightForWidth())
        self.notifIcon.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(15)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.notifIcon.setFont(font)
        self.notifIcon.setStyleSheet("  padding: 0px 0px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-width: 0px;\n"
"    font-family:\'Georgia\';\n"
"    margin: 0px;")
        self.notifIcon.setObjectName("notifIcon")
        self.horizontalLayout_5.addWidget(self.notifIcon)
        self.notifText = QtWidgets.QLabel(parent=self.notifFrame)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.notifText.setFont(font)
        self.notifText.setStyleSheet("\n"
"    padding: 0px 0px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-width: 0px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 5px;")
        self.notifText.setWordWrap(True)
        self.notifText.setObjectName("notifText")
        self.horizontalLayout_5.addWidget(self.notifText)
        self.notifDelButton = QtWidgets.QPushButton(parent=self.notifFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notifDelButton.sizePolicy().hasHeightForWidth())
        self.notifDelButton.setSizePolicy(sizePolicy)
        self.notifDelButton.setMaximumSize(QtCore.QSize(10, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.notifDelButton.setFont(font)
        self.notifDelButton.setStyleSheet("    background-color: transparent;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 0px;\n"
"    border-radius: 15px;\n"
"")
        self.notifDelButton.setObjectName("notifDelButton")
        self.horizontalLayout_5.addWidget(self.notifDelButton)
        self.verticalLayout.addWidget(self.notifFrame)
        self.openfolderbutton = QtWidgets.QPushButton(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.openfolderbutton.setFont(font)
        self.openfolderbutton.setStyleSheet("QPushButton{\n"
"color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 7px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"}\n"
"\n"
":hover{\n"
"background-color:black;\n"
"}")
        self.openfolderbutton.setObjectName("openfolderbutton")
        self.verticalLayout.addWidget(self.openfolderbutton)
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setStyleSheet("color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"height: 5px;")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.tablist = QtWidgets.QTabWidget(parent=self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 39, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 39, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(39, 39, 39))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 36, 36))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.tablist.setPalette(palette)
        self.tablist.setStyleSheet("    color: white;\n"
"    background-color: #242424;\n"
"border-radius: 15px;\n"
"\n"
"")
        self.tablist.setTabPosition(QtWidgets.QTabWidget.TabPosition.West)
        self.tablist.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tablist.setElideMode(QtCore.Qt.TextElideMode.ElideNone)
        self.tablist.setObjectName("tablist")
        self.List = QtWidgets.QWidget()
        self.List.setStyleSheet("")
        self.List.setObjectName("List")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.List)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.List)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 976, 504))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        spacerItem1 = QtWidgets.QSpacerItem(3000, 5, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.tablist.addTab(self.List, "")
        self.Object = QtWidgets.QWidget()
        self.Object.setStyleSheet("")
        self.Object.setObjectName("Object")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Object)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.OBJObjectName = QtWidgets.QLabel(parent=self.Object)
        self.OBJObjectName.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(24)
        font.setBold(False)
        self.OBJObjectName.setFont(font)
        self.OBJObjectName.setObjectName("OBJObjectName")
        self.verticalLayout_5.addWidget(self.OBJObjectName)
        self.OBJObjectDesc = QtWidgets.QLabel(parent=self.Object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OBJObjectDesc.sizePolicy().hasHeightForWidth())
        self.OBJObjectDesc.setSizePolicy(sizePolicy)
        self.OBJObjectDesc.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(15)
        font.setBold(False)
        self.OBJObjectDesc.setFont(font)
        self.OBJObjectDesc.setObjectName("OBJObjectDesc")
        self.verticalLayout_5.addWidget(self.OBJObjectDesc)
        self.horizontalWidget = QtWidgets.QWidget(parent=self.Object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalWidget.sizePolicy().hasHeightForWidth())
        self.horizontalWidget.setSizePolicy(sizePolicy)
        self.horizontalWidget.setMinimumSize(QtCore.QSize(0, 50))
        self.horizontalWidget.setStyleSheet("QPushButton{\n"
"color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 7px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"    margin-bottom: 0px;\n"
"    margin-top: 5px;\n"
"}")
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.openFolderButton = QtWidgets.QPushButton(parent=self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.openFolderButton.setFont(font)
        self.openFolderButton.setStyleSheet(":hover{\n"
"background-color:black;\n"
"}")
        self.openFolderButton.setObjectName("openFolderButton")
        self.horizontalLayout_3.addWidget(self.openFolderButton)
        self.delOBJButton = QtWidgets.QPushButton(parent=self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.delOBJButton.setFont(font)
        self.delOBJButton.setStyleSheet(":hover{\n"
"background-color:black;\n"
"border-color:#A40000;\n"
"}")
        self.delOBJButton.setObjectName("delOBJButton")
        self.horizontalLayout_3.addWidget(self.delOBJButton)
        self.back2listButton = QtWidgets.QPushButton(parent=self.horizontalWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.back2listButton.setFont(font)
        self.back2listButton.setStyleSheet(":hover{\n"
"background-color:black;\n"
"}")
        self.back2listButton.setObjectName("back2listButton")
        self.horizontalLayout_3.addWidget(self.back2listButton)
        self.verticalLayout_5.addWidget(self.horizontalWidget)
        self.widget = QtWidgets.QWidget(parent=self.Object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 50))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.DestinationFolderButton = QtWidgets.QPushButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DestinationFolderButton.sizePolicy().hasHeightForWidth())
        self.DestinationFolderButton.setSizePolicy(sizePolicy)
        self.DestinationFolderButton.setMinimumSize(QtCore.QSize(250, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.DestinationFolderButton.setFont(font)
        self.DestinationFolderButton.setStyleSheet(":hover{\n"
"background-color:black;\n"
"}\n"
"QPushButton{\n"
"    color: white;\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 7px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: #45CE7F;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"}")
        self.DestinationFolderButton.setObjectName("DestinationFolderButton")
        self.horizontalLayout_6.addWidget(self.DestinationFolderButton)
        self.ExportButton = QtWidgets.QPushButton(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.ExportButton.setFont(font)
        self.ExportButton.setStyleSheet(":hover{\n"
"background-color:black;\n"
"}\n"
"QPushButton{\n"
"    color: white;\n"
"    background-color: #45CE7F;\n"
"    padding: 7px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: #45CE7F;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"}")
        self.ExportButton.setObjectName("ExportButton")
        self.horizontalLayout_6.addWidget(self.ExportButton)
        self.verticalLayout_5.addWidget(self.widget)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.label_8 = QtWidgets.QLabel(parent=self.Object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.TagManagementWidget = QtWidgets.QWidget(parent=self.Object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TagManagementWidget.sizePolicy().hasHeightForWidth())
        self.TagManagementWidget.setSizePolicy(sizePolicy)
        self.TagManagementWidget.setMinimumSize(QtCore.QSize(0, 70))
        self.TagManagementWidget.setMaximumSize(QtCore.QSize(16777215, 51))
        self.TagManagementWidget.setStyleSheet("margin: 0px;\n"
"padding: 0px;")
        self.TagManagementWidget.setObjectName("TagManagementWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.TagManagementWidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.OBJWidgetContainer = QtWidgets.QFrame(parent=self.TagManagementWidget)
        self.OBJWidgetContainer.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.OBJWidgetContainer.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.OBJWidgetContainer.setObjectName("OBJWidgetContainer")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.OBJWidgetContainer)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.TagEditButton = QtWidgets.QPushButton(parent=self.OBJWidgetContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TagEditButton.sizePolicy().hasHeightForWidth())
        self.TagEditButton.setSizePolicy(sizePolicy)
        self.TagEditButton.setMinimumSize(QtCore.QSize(0, 20))
        self.TagEditButton.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.TagEditButton.setFont(font)
        self.TagEditButton.setStyleSheet(":hover{\n"
"background-color:black;\n"
"}\n"
"QPushButton{\n"
"background-color: #247C49;\n"
"     padding: 0px 10px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 0px;\n"
"    border-radius: 5px;\n"
"    margin: 0px;\n"
"}")
        self.TagEditButton.setObjectName("TagEditButton")
        self.horizontalLayout_9.addWidget(self.TagEditButton)
        self.horizontalLayout_7.addWidget(self.OBJWidgetContainer)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label_9 = QtWidgets.QLabel(parent=self.TagManagementWidget)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.OBJTagBox = QtWidgets.QComboBox(parent=self.TagManagementWidget)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.OBJTagBox.setFont(font)
        self.OBJTagBox.setStyleSheet("QComboBox{\n"
"color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 6px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"   border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"}")
        self.OBJTagBox.setObjectName("OBJTagBox")
        self.OBJTagBox.addItem("")
        self.horizontalLayout_7.addWidget(self.OBJTagBox)
        self.verticalLayout_6.addWidget(self.TagManagementWidget)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem3)
        self.OBJPicturesContainer = QtWidgets.QWidget(parent=self.Object)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OBJPicturesContainer.sizePolicy().hasHeightForWidth())
        self.OBJPicturesContainer.setSizePolicy(sizePolicy)
        self.OBJPicturesContainer.setMaximumSize(QtCore.QSize(16777215, 200))
        self.OBJPicturesContainer.setStyleSheet("#OBJPicturesContainer{\n"
"color: rgb(218, 218, 218);\n"
"    background-color: transparent;\n"
"    padding: 20px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 0px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"    margin-top: 0px;\n"
"}")
        self.OBJPicturesContainer.setObjectName("OBJPicturesContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.OBJPicturesContainer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.OBJlabel_1 = QtWidgets.QLabel(parent=self.OBJPicturesContainer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OBJlabel_1.sizePolicy().hasHeightForWidth())
        self.OBJlabel_1.setSizePolicy(sizePolicy)
        self.OBJlabel_1.setMinimumSize(QtCore.QSize(150, 150))
        self.OBJlabel_1.setMaximumSize(QtCore.QSize(150, 150))
        self.OBJlabel_1.setText("")
        self.OBJlabel_1.setPixmap(QtGui.QPixmap("no_image.svg"))
        self.OBJlabel_1.setScaledContents(True)
        self.OBJlabel_1.setObjectName("OBJlabel_1")
        self.horizontalLayout_2.addWidget(self.OBJlabel_1)
        self.verticalLayout_6.addWidget(self.OBJPicturesContainer)
        self.tablist.addTab(self.Object, "")
        self.Tag_Management = QtWidgets.QWidget()
        self.Tag_Management.setObjectName("Tag_Management")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Tag_Management)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(parent=self.Tag_Management)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.verticalLayout_7.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(parent=self.Tag_Management)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setStyleSheet("QPushButton{\n"
"color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 7px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"    margin-bottom: 0px;\n"
"    margin-top: 0px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.back2listButton_2 = QtWidgets.QPushButton(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.back2listButton_2.setFont(font)
        self.back2listButton_2.setObjectName("back2listButton_2")
        self.horizontalLayout_4.addWidget(self.back2listButton_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.label_10 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.TMTagBox = QtWidgets.QComboBox(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TMTagBox.sizePolicy().hasHeightForWidth())
        self.TMTagBox.setSizePolicy(sizePolicy)
        self.TMTagBox.setMinimumSize(QtCore.QSize(200, 0))
        self.TMTagBox.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.TMTagBox.setFont(font)
        self.TMTagBox.setStyleSheet("QComboBox{\n"
"color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 6px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"   border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"}")
        self.TMTagBox.setObjectName("TMTagBox")
        self.horizontalLayout_4.addWidget(self.TMTagBox)
        self.TMSaveButton = QtWidgets.QPushButton(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TMSaveButton.sizePolicy().hasHeightForWidth())
        self.TMSaveButton.setSizePolicy(sizePolicy)
        self.TMSaveButton.setMinimumSize(QtCore.QSize(300, 0))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.TMSaveButton.setFont(font)
        self.TMSaveButton.setStyleSheet(":hover{\n"
"background-color:black;\n"
"}\n"
"QPushButton{\n"
"    color: white;\n"
"    background-color: #45CE7F;\n"
"    padding: 7px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: #45CE7F;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"}")
        self.TMSaveButton.setObjectName("TMSaveButton")
        self.horizontalLayout_4.addWidget(self.TMSaveButton)
        self.TMDeleteButton = QtWidgets.QPushButton(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.TMDeleteButton.setFont(font)
        self.TMDeleteButton.setStyleSheet(":hover{\n"
"background-color:black;\n"
"border-color:#A40000;\n"
"}\n"
"QPushButton{\n"
"background-color: #A40000;\n"
"}")
        self.TMDeleteButton.setObjectName("TMDeleteButton")
        self.horizontalLayout_4.addWidget(self.TMDeleteButton)
        self.verticalLayout_7.addWidget(self.frame_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_7.addItem(spacerItem5)
        self.frame_3 = QtWidgets.QFrame(parent=self.Tag_Management)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_3.setStyleSheet("QPushButton{\n"
"color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 7px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"    margin-bottom: 0px;\n"
"    margin-top: 0px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.TMNameEditor = QtWidgets.QLineEdit(parent=self.frame_3)
        self.TMNameEditor.setMaximumSize(QtCore.QSize(200, 16777215))
        self.TMNameEditor.setStyleSheet("color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 6px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;")
        self.TMNameEditor.setObjectName("TMNameEditor")
        self.gridLayout.addWidget(self.TMNameEditor, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Comfortaa")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 5, 1, 1)
        self.TMColorSelectorButton = QtWidgets.QPushButton(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.TMColorSelectorButton.setFont(font)
        self.TMColorSelectorButton.setStyleSheet("QPushButton{\n"
"    border-color:qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:1, stop:0 rgba(255, 0, 0, 255), stop:0.094 rgba(210, 224, 36, 255), stop:0.194 rgba(68, 193, 48, 255), stop:0.306 rgba(36, 204, 54, 255), stop:0.428 rgba(50, 235, 149, 255), stop:0.538 rgba(112, 175, 245, 255), stop:0.652 rgba(36, 73, 209, 255), stop:0.766 rgba(130, 21, 191, 255), stop:0.884 rgba(168, 42, 83, 255), stop:1 rgba(255, 0, 0, 255));\n"
"    color: white;\n"
"    border-width: 1px;\n"
"}")
        self.TMColorSelectorButton.setObjectName("TMColorSelectorButton")
        self.gridLayout.addWidget(self.TMColorSelectorButton, 1, 1, 1, 1)
        self.TMColorHexEditor = QtWidgets.QLineEdit(parent=self.frame_3)
        self.TMColorHexEditor.setMaximumSize(QtCore.QSize(200, 16777215))
        self.TMColorHexEditor.setStyleSheet("color: rgb(218, 218, 218);\n"
"    background-color: rgba(0, 0, 0, 0.37);\n"
"    padding: 6px 20px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;")
        self.TMColorHexEditor.setObjectName("TMColorHexEditor")
        self.gridLayout.addWidget(self.TMColorHexEditor, 1, 6, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem6, 1, 7, 1, 1)
        self.TMClearFieldsButton = QtWidgets.QPushButton(parent=self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.TMClearFieldsButton.setFont(font)
        self.TMClearFieldsButton.setObjectName("TMClearFieldsButton")
        self.gridLayout.addWidget(self.TMClearFieldsButton, 2, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.TMColorPreviewWidget = QtWidgets.QWidget(parent=self.Tag_Management)
        self.TMColorPreviewWidget.setMinimumSize(QtCore.QSize(0, 50))
        self.TMColorPreviewWidget.setStyleSheet("QWidget{\n"
"    background-color: #45CE7F;\n"
"    padding: 2px 6px;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    border-color: grey;\n"
"    border-style:solid;\n"
"    border-width: 0px;\n"
"    border-radius: 15px;\n"
"    font-family:\'Courier New\', Courier, monospace;\n"
"    margin: 10px;\n"
"}")
        self.TMColorPreviewWidget.setObjectName("TMColorPreviewWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.TMColorPreviewWidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_11 = QtWidgets.QLabel(parent=self.TMColorPreviewWidget)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.verticalLayout_7.addWidget(self.TMColorPreviewWidget)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_7.addItem(spacerItem7)
        self.tablist.addTab(self.Tag_Management, "")
        self.horizontalLayout.addWidget(self.tablist)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1248, 20))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(parent=self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuedit = QtWidgets.QMenu(parent=self.menubar)
        self.menuedit.setObjectName("menuedit")
        self.menutool = QtWidgets.QMenu(parent=self.menubar)
        self.menutool.setObjectName("menutool")
        self.menuhelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionimport = QtGui.QAction(parent=MainWindow)
        self.actionimport.setObjectName("actionimport")
        self.actionopen_folder = QtGui.QAction(parent=MainWindow)
        self.actionopen_folder.setObjectName("actionopen_folder")
        self.actionsearch = QtGui.QAction(parent=MainWindow)
        self.actionsearch.setObjectName("actionsearch")
        self.actionwebsite = QtGui.QAction(parent=MainWindow)
        self.actionwebsite.setObjectName("actionwebsite")
        self.actionabout = QtGui.QAction(parent=MainWindow)
        self.actionabout.setObjectName("actionabout")
        self.actionconfigure = QtGui.QAction(parent=MainWindow)
        self.actionconfigure.setObjectName("actionconfigure")
        self.actionexit = QtGui.QAction(parent=MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionRefresh_app = QtGui.QAction(parent=MainWindow)
        self.actionRefresh_app.setObjectName("actionRefresh_app")
        self.menufile.addAction(self.actionimport)
        self.menufile.addAction(self.actionopen_folder)
        self.menuedit.addAction(self.actionconfigure)
        self.menutool.addAction(self.actionsearch)
        self.menutool.addAction(self.actionRefresh_app)
        self.menuhelp.addAction(self.actionwebsite)
        self.menuhelp.addAction(self.actionabout)
        self.menuhelp.addAction(self.actionexit)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        self.menubar.addAction(self.menutool.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tablist.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MatterIndex"))
        self.label_2.setText(_translate("MainWindow", "Find by name:"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.label_3.setText(_translate("MainWindow", "Tags:"))
        self.ManageTagsButton.setText(_translate("MainWindow", "Manage →"))
        self.notifIcon.setText(_translate("MainWindow", "ⅰ"))
        self.notifText.setText(_translate("MainWindow", "Notification"))
        self.notifDelButton.setText(_translate("MainWindow", "✕"))
        self.openfolderbutton.setText(_translate("MainWindow", "Open root folder"))
        self.tablist.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.tablist.setTabText(self.tablist.indexOf(self.List), _translate("MainWindow", "List"))
        self.OBJObjectName.setText(_translate("MainWindow", "Object Name"))
        self.OBJObjectDesc.setText(_translate("MainWindow", "Object desc"))
        self.openFolderButton.setText(_translate("MainWindow", "Open folder"))
        self.delOBJButton.setText(_translate("MainWindow", "Delete Object"))
        self.back2listButton.setText(_translate("MainWindow", "← Back to list"))
        self.DestinationFolderButton.setText(_translate("MainWindow", "Destination folder"))
        self.ExportButton.setText(_translate("MainWindow", "Export"))
        self.label_8.setText(_translate("MainWindow", "Tags:"))
        self.TagEditButton.setText(_translate("MainWindow", "All"))
        self.label_9.setText(_translate("MainWindow", "Add tag:"))
        self.OBJTagBox.setItemText(0, _translate("MainWindow", "Add Tag"))
        self.tablist.setTabText(self.tablist.indexOf(self.Object), _translate("MainWindow", "Objet"))
        self.label_4.setText(_translate("MainWindow", "Tag Management:"))
        self.back2listButton_2.setText(_translate("MainWindow", "← Back to list"))
        self.label_10.setText(_translate("MainWindow", "Tag:"))
        self.TMSaveButton.setText(_translate("MainWindow", "Save"))
        self.TMDeleteButton.setText(_translate("MainWindow", "Delete"))
        self.label_6.setText(_translate("MainWindow", "Define color:"))
        self.label_5.setText(_translate("MainWindow", "Define Name:"))
        self.label_7.setText(_translate("MainWindow", "Hex:"))
        self.TMColorSelectorButton.setText(_translate("MainWindow", "Color Palette..."))
        self.TMColorHexEditor.setText(_translate("MainWindow", "#45CE7F"))
        self.TMClearFieldsButton.setText(_translate("MainWindow", "Clear Fields"))
        self.label_11.setText(_translate("MainWindow", "Color preview:"))
        self.tablist.setTabText(self.tablist.indexOf(self.Tag_Management), _translate("MainWindow", "Tag management"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuedit.setTitle(_translate("MainWindow", "Edit"))
        self.menutool.setTitle(_translate("MainWindow", "Tool"))
        self.menuhelp.setTitle(_translate("MainWindow", "Help"))
        self.actionimport.setText(_translate("MainWindow", "import"))
        self.actionopen_folder.setText(_translate("MainWindow", "open folder"))
        self.actionsearch.setText(_translate("MainWindow", "search"))
        self.actionwebsite.setText(_translate("MainWindow", "website"))
        self.actionabout.setText(_translate("MainWindow", "about"))
        self.actionconfigure.setText(_translate("MainWindow", "configure"))
        self.actionexit.setText(_translate("MainWindow", "exit"))
        self.actionRefresh_app.setText(_translate("MainWindow", "Refresh app"))
